# Site settings
title: jangirrishabh.io
email: jangirrishabh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Excited by Electrons
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jangirrishabh.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title:output_ext #permalink: /:categories/:year/:month/:day/:title:output_ext
#url: "http://localhost:4000" # the base hostname & protocol for your site
github_username:  jangirrishabh
#twitter_username: RishabhJangir


# Build settings
markdown: kramdown
