# Site settings
title: Rishabh Jangir Blog
email: jangirrishabh@gmail.com
description: "Excited by electrons."
baseurl: ""
url: "http://jangirrishabh.github.io"
twitter_username: RishabhJangir
github_username:  jangirrishabh


# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
